apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaosmonkey.fullname" . }}
  labels:
    {{- include "chaosmonkey.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chaosmonkey.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
